/**
 * 渲染一个 new-api 站点的 compose 项目。基于 calciumion/new-api 官方镜像。
 * 与 sub2api 的差异：容器内端口 3000；DB 由 SQL_DSN 决定（不设=SQLite）；
 * 每站独立 SESSION_SECRET（否则重启踢登录、多节点 session 不通）；健康检查 /api/status。
 */

export interface NewapiComposeInput {
  slug: string;
  /** calciumion/new-api 的 image tag，禁止 latest */
  version: string;
  hostPort: number;
  sessionSecret: string;
  /** 可选：外部 DB DSN（shared 模式）。留空=容器内 SQLite */
  sqlDsn?: string;
  timezone?: string;
}

export function renderNewapiEnv(input: NewapiComposeInput): string {
  const lines = [
    `NEWAPI_VERSION=${input.version}`,
    `SERVER_PORT=${input.hostPort}`,
    `SESSION_SECRET=${input.sessionSecret}`,
    `SQL_DSN=${input.sqlDsn ?? ''}`,
    `TZ=${input.timezone ?? 'Asia/Shanghai'}`,
  ];
  return lines.join('\n') + '\n';
}

export function renderNewapiCompose(input: NewapiComposeInput): string {
  if (input.version === 'latest') {
    throw new Error('version must be pinned; "latest" is not allowed');
  }
  return `# Generated by relay-panel for site "${input.slug}" — do not edit by hand.
services:
  newapi:
    image: calciumion/new-api:\${NEWAPI_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:\${SERVER_PORT}:3000"
    environment:
      - TZ=\${TZ}
      - SESSION_SECRET=\${SESSION_SECRET}
      - SQL_DSN=\${SQL_DSN}
      - NODE_TYPE=master
    volumes:
      - newapi_data:/data
      - newapi_logs:/app/logs
    command: ["--log-dir", "/app/logs"]
    healthcheck:
      test: ["CMD", "wget", "-q", "-T", "5", "-O", "/dev/null", "http://localhost:3000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

volumes:
  newapi_data:
  newapi_logs:
`;
}
