/**
 * 渲染一个 sub2api 站点的 compose 项目。
 * 基于上游 deploy/docker-compose.yml（weishaw/sub2api）改写：
 * - 钉版本 tag，禁止 latest
 * - 去掉 container_name，让 compose 按 project 前缀命名（多站共存）
 * - 引擎端口只绑 127.0.0.1，公网流量走反代
 * - PG/Redis 不暴露宿主机端口
 */

export interface Sub2apiComposeInput {
  slug: string;
  /** weishaw/sub2api 的镜像 tag */
  version: string;
  hostPort: number;
  adminEmail: string;
  /** 以下密钥由 provisioner 生成后传入，渲染进 .env（.env 文件权限受数据目录保护） */
  postgresPassword: string;
  jwtSecret: string;
  totpEncryptionKey: string;
  adminPassword: string;
  timezone?: string;
}

export function renderSub2apiEnv(input: Sub2apiComposeInput): string {
  const lines = [
    `SUB2API_VERSION=${input.version}`,
    `SERVER_PORT=${input.hostPort}`,
    `POSTGRES_PASSWORD=${input.postgresPassword}`,
    `JWT_SECRET=${input.jwtSecret}`,
    `TOTP_ENCRYPTION_KEY=${input.totpEncryptionKey}`,
    `ADMIN_EMAIL=${input.adminEmail}`,
    `ADMIN_PASSWORD=${input.adminPassword}`,
    `TZ=${input.timezone ?? 'Asia/Shanghai'}`,
  ];
  return lines.join('\n') + '\n';
}

export function renderSub2apiCompose(input: Sub2apiComposeInput): string {
  if (input.version === 'latest') {
    throw new Error('version must be pinned; "latest" is not allowed');
  }
  return `# Generated by relay-panel for site "${input.slug}" — do not edit by hand.
services:
  sub2api:
    image: weishaw/sub2api:\${SUB2API_VERSION}
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    ports:
      - "127.0.0.1:\${SERVER_PORT}:8080"
    volumes:
      - sub2api_data:/app/data
    environment:
      - AUTO_SETUP=true
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - SERVER_MODE=release
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=sub2api
      - DATABASE_PASSWORD=\${POSTGRES_PASSWORD}
      - DATABASE_DBNAME=sub2api
      - DATABASE_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ADMIN_EMAIL=\${ADMIN_EMAIL}
      - ADMIN_PASSWORD=\${ADMIN_PASSWORD}
      - JWT_SECRET=\${JWT_SECRET}
      - TOTP_ENCRYPTION_KEY=\${TOTP_ENCRYPTION_KEY}
      - TZ=\${TZ}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-q", "-T", "5", "-O", "/dev/null", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 100000
        hard: 100000
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # postgres:18-alpine 默认 PGDATA 不在挂载卷内，必须显式设置，否则 down/up 数据丢失
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER=sub2api
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
      - POSTGRES_DB=sub2api
      - TZ=\${TZ}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sub2api -d sub2api"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--appendonly", "yes", "--appendfsync", "everysec"]
    environment:
      - TZ=\${TZ}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  sub2api_data:
  postgres_data:
  redis_data:
`;
}
